
title: Klay Adams' Personal Site
author:
 #name: Klay Adams
 email: 
   personal: klayaa@me.com
 github_username: klay326
header_pages:
 - page.md
 - another_page.md
message: Write some cool footer message here
style: dark
baseurl: "Klay Adams" # the subpath of your site, e.g. /blog
url: "https://klayadams.com" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: Forthoney/consolo 
plugins:
  - jekyll-feed